name: build
on:
  push:
    branches: [ "homework-4-ci" ]
  pull_request:
    branches:
      [ "main", "homework-4" ]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Set token
        run: |
          echo "TOKEN=${{ secrets.TOKEN }}" >> .env

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Run format
        run: dart format --set-exit-if-changed .

      - name: Run codegen
        run: flutter pub run build_runner build -d

      - name: Analyze project
        run: flutter analyze --no-fatal-infos

  tests:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Set token
        run: |
          echo "TOKEN=${{ secrets.TOKEN }}" >> .env

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '19'
          cache: gradle

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

  deploy:
    name: Deploy to Firebase App Distribution
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Set token
        run: |
          echo "TOKEN=${{ secrets.TOKEN }}" >> .env

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '19'
          cache: gradle

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Run codegen
        run: flutter pub run build_runner build -d

      - name: Build apk
        run: flutter build apk --flavor prod --target lib/main_prod.dart

      - name: Upload apk
        uses: actions/upload-artifact@v4
        with:
          path: build/app/outputs/flutter-apk/app-prod-release.apk

      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          file: build/app/outputs/flutter-apk/app-release.apk
